const router = require('express').Router()
const authUser = require('./authUser')
const logoutUser = require('./logoutUser')
const authorize = require('./authorize')
const post = require('./post')
const user = require('./user')
const news = require('./news')
const suggestion = require('./suggestion')
const message = require('./message')
const search = require('./search')

router.use('/', authUser)
router.use('/', logoutUser)
router.use('/', authorize)
router.use('/', post)
router.use('/', user)
router.use('/', news)
router.use('/', suggestion)
router.use('/', message)
router.use('/', search)

module.exports = router