const router = require('express').Router()
const login = require('./login')
const logout = require('./logout')
const authorize = require('./authorize')
const post = require('./post')
const user = require('./user')
const news = require('./news')
const suggestion = require('./suggestion')
const message = require('./message')
const search = require('./search')
const like = require('./like')
const dislike = require('./dislike')
const subscribe = require('./subscribe')
const unsubscribe = require('./unsubscribe')

router.use('/', login)
router.use('/', logout)
router.use('/', authorize)
router.use('/', post)
router.use('/', user)
router.use('/', news)
router.use('/', suggestion)
router.use('/', message)
router.use('/', search)
router.use('/', like)
router.use('/', dislike)
router.use('/', subscribe)
router.use('/', unsubscribe)

module.exports = router